item_properties:
- key: testname
  type: text
  value:
  mandatory: true
  direction: input
  help: A unique test name

- key: test_runner_id
  type: text
  value:
  mandatory: true
  direction: input
  help: The test runner pid

- key: test_input
  type: json
  value:
  editor: json
  mandatory: false
  direction: input
  help: Test input json

- key: test_output
  type: json
  value:
  editor: hidden
  mandatory: false
  direction: output
  help: Test output json

timeout: 3600
type: record